apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: playground-namespace
spec:
  type: LoadBalancer
  selector:
    app: playground
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
  namespace: playground-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - name: playground
          image: tejunior/playground
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
